#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

yarn run check-lint ||
(
       echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
       false;
)

yarn run check-types ||
(
   echo 'Failed Type check.'
   false;
)

yarn run build ||
(
   echo 'React build failed: View the errors above to see why.'
   false;
)
